name: Update Product Description on FPlugins.com
on:
  workflow_call:
    inputs:
      product_id:
        type: string
        required: true
    secrets:
      fplugins_secret:
        required: true
jobs:
  update-description:
    name: Update Product Description on FPlugins.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Read and Encode README Content
        id: readme
        run: |
          content=$(cat README.md | jq -Rs .)
          echo "description=$content" >> $GITHUB_OUTPUT
        shell: bash

      - name: Update Product Description
        env:
          FPLUGINS_SECRET: ${{ secrets.fplugins_secret }}
          PRODUCT_ID: ${{ inputs.product_id }}
          README_CONTENT: ${{ steps.readme.outputs.description }}
        if: env.FPLUGINS_SECRET != null
        run: |
          json_payload=$(jq -n --arg desc "$README_CONTENT" '{"Description": $desc}')
          
          response=$(curl -s -w "\n%{http_code}" -X PUT "https://api.fplugins.com/products/$PRODUCT_ID/description" \
            -H "accept: */*" \
            -H "Content-Type: application/json" \
            -H "Secret: $FPLUGINS_SECRET" \
            -d "$json_payload")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response body:"
          echo "$body"
          echo "Status code: $http_code"
          
          if [ "$http_code" -ge 400 ]; then
            echo "Error: API request failed with status code $http_code"
            exit 1
          fi
        shell: bash

      - name: Debug Output (if failed)
        if: failure()
        run: |
          echo "JSON Payload (first 1000 characters):"
          echo "$json_payload" | cut -c1-1000
          echo "..."
        shell: bash