name: Build & Create Rocket Plugin GitHub Release

on:
  workflow_call:
    inputs:
      project_name:
        type: string
        default: ${{ github.event.repository.name }}
      project_path:
        type: string
        default: "./${{ github.event.repository.name }}/${{ github.event.repository.name }}.csproj"
      build_directory:
        type: string
        default: "./${{ github.event.repository.name }}/bin/Release/net48"
      plugin_file_name:
        type: string
        default: "${{ github.event.repository.name }}.dll"
  
jobs:
  build:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v0
        with:
          file: ${{ inputs.project_path }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip Rocket release artifacts
        run: |
          mkdir -p ./release/Plugins ./release/Libraries
          mv ${{ inputs.build_directory }}/${{ inputs.plugin_file_name }} ./release/Plugins/
          if [ -n "$(find ${{ inputs.build_directory }} -maxdepth 1 -name '*.dll')" ]; then
            mv ${{ inputs.build_directory }}/*.dll ./release/Libraries/
          fi
          cd ./release/
          zip -qr ./../release.zip *
        shell: bash
        
      - name: Check tag
        id: check_tag
        uses: mukunku/tag-exists-action@v1.6.0
        with: 
          tag: v${{ steps.package_version.outputs.version }}

      - name: Get last commit message
        id: get_last_commit
        run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
        
      - name: Create release
        id: create_release
        if: steps.check_tag.outputs.exists == 'false' 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          release_name: "${{ github.event.repository.name }} v${{ steps.package_version.outputs.version }}"
          body: "${{ steps.get_last_commit.outputs.message }}"
          draft: true
          prerelease: false
      
      - name: Upload Rocket release asset
        if: steps.check_tag.outputs.exists == 'false' 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: "/${{ github.event.repository.name }}-v${{ steps.package_version.outputs.version }}.zip"
          asset_content_type: application/zip

      - name: Upload Release Assets
        id: upload-release-assets
        if: steps.check_tag.outputs.exists == 'false' 
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: ./*.unitypackage

      - uses: eregon/publish-release@v1
        if: steps.check_tag.outputs.exists == 'false' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
